# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr: none

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    displayName: Use node 15.7.x
    inputs:
      versionSpec: '15.7.x'

  - script: npm config set msvs_version 2017 --global
    displayName: Set Visual Studio to 2017

  - script: npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe"
    displayName: Set Visual Studio msbuild path

  - script: npm ci --no-optional
    displayName: Install

  - script: npm run lint
    displayName: Lint

  - script: npm run build:site
    displayName: Build site

  - task: AzureFileCopy@4
    displayName: Deploy site
    inputs:
      sourcePath: $(System.DefaultWorkingDirectory)/site/dist/*
      azureSubscription: 'MSFTDOCS - AtlasDesign Content Publisher'
      destination: azureBlob
      storage: atlasdesignpublic
      containerName: $web
