# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr: none

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    displayName: Use node 15.7.x
    inputs:
      versionSpec: '15.7.x'

  - script: npm -v
    displayName: Print npm version

  - script: npm i -g node-gyp@latest
    displayName: Install latest version of node-gyp

  - script: npm config set msvs_version 2015 -g
    displayName: Use Visual Studio 2015

  - script: npm ci --no-optional
    displayName: Install

  - script: npm run lint
    displayName: Lint

  - script: npm run build:site
    displayName: Build site

  - task: AzureFileCopy@4
    displayName: Deploy site
    inputs:
      sourcePath: $(System.DefaultWorkingDirectory)/site/dist/*
      azureSubscription: 'MSFTDOCS - AtlasDesign Content Publisher'
      destination: azureBlob
      storage: atlasdesignpublic
      containerName: $web
