# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

steps:
  - script: yarn
    displayName: Install

  - script: yarn lint
    displayName: Lint

  - script: yarn
    displayName: yarn build:site

  - script: echo 'Test'
    displayName: echo

  - task: AzureFileCopy@4
    displayName: Deploy main site
    inputs:
      sourcePath: $(System.DefaultWorkingDirectory)/site/dist/
      azureSubscription: 'MSFTDOCS - AtlasDesign Content Publisher'
      destination: azureBlob
      storage: atlasdesignpublic
      containerName: $web
